services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis