global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nodejs"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
